%YAML 1.2
# -*- coding: UTF-8, tab-width: 4 -*-
---

env:
    node: true
    es6: true

plugins:
    - "package-json"

extends:
    - "eslint:recommended"

rules:
    comma-dangle: ["error", {"objects": "always-multiline"}] # +4 errors
    quotes: ["error", "single"] # +33 errors
    semi: ["error", "never"] # +1 error

...
