%YAML 1.2
# -*- coding: UTF-8, tab-width: 4 -*-
---

env:
    node: true
    es6: true

plugins:
    - "package-json"

extends:
    - "eslint:recommended"
    - "@instaffogmbh/eslint-config-instaffo"

"rules":
    "package-json/valid-package-def": error
    "package-json/sort-collections": error
    "package-json/namespaced-requires-public": error
    "package-json/public-requires-namespaced": error
    "package-json/require-properties":
        - error
        - - "private"

...
